#!/usr/bin/env python3.11
"""ALIAS GATE — a real instrument for the `OSValidationTest` aliasing number.

Session 92, opened by CLAUDE.md "Open work" item 6.

WHY THIS EXISTS
---------------
Shipping `jfetSatNeg` 0.76054 -> 1.9 in session 91 moved `OSValidationTest`'s 8x alias/signal
figure at amp 0.35 from **-23.6 to -17.3 dB**, the first movement in 46 sessions. Attribution is
exact (reverting that one constant reproduces the old record to the digit), but **whether the
number measures aliasing at all was never established**. The handover lists three reasons to
doubt it and one reason to believe it, and `measurement-discipline.md` is explicit that an
argument for why an instrument must be wrong is not a measurement of it being wrong
(`instrument-defect-is-a-hypothesis`, s90) -- so this tool measures the instrument first, against
signals whose alias content is known by construction, and only then measures the chain.

WHAT THE OLD METRIC DOES (reimplemented verbatim as `metric_old`, so the two can be run on the
SAME samples and the difference is the analysis, never the render):

  * renders a 2500 Hz sine at fs = 48000 through `PedalDSP`, discards 0.3 s, keeps 32768 samples
  * Hann-windows the FIRST 16384 of them, takes |FFT|
  * calls a bin "signal" if it is within +-3 bins of an integer multiple of f0, "alias" otherwise
  * reports 10*log10(alias_power / signal_power)

Three things in that are not properties of the chain:

  (a) **f0 is not bin-exact.** 2500 / (48000/16384) = 853.333 bins. Every harmonic whose order is
      not a multiple of 3 sits a third of a bin off-grid, so its Hann skirt runs past the +-3 bin
      mask and is counted as alias. The leaked fraction is fixed, so the metric has a PEDESTAL --
      and the pedestal grows with harmonic content, which is exactly what `jfetSatNeg` changes.
  (b) **0.3 s is not settled.** `MasterOut` is two ~0.72 Hz high-passes (tau = 0.22 s). An
      asymmetric clipper puts a DC step into them, so the analysis window still contains a
      decaying LF ramp -- energy at bins 1..50, where `round(f/f0) == 0` classifies it as alias.
      DC offset is generated by even-order asymmetry, i.e. again exactly what `jfetSatNeg` changes.
  (c) real aliasing.

`metric_new` removes (a) and (b) by construction rather than by tolerance:

  * f0 is chosen bin-exact (f0 = K*fs/M), so the stimulus is periodic in exactly M samples. The
    chain is time-invariant and the OS factor divides M, so the steady-state output is periodic in
    M too -- a RECTANGULAR window then has zero leakage and every harmonic AND every fold of a
    harmonic lands dead on a bin. No mask width is needed and none is used.
  * the settle is 4 s (18 tau), and the LF region is reported as its own bucket instead of being
    summed into "alias", so any residual shows up labelled rather than disguised.
  * harmonic bins are {n*K : n*K < M/2}. A harmonic above Nyquist folds to |n*K - M| and is
    correctly counted as ALIAS, because a band-limited model would not produce it at all.

GATES (`--selftest`) -- every one is a signal whose answer is known before it is measured, and
each is chosen to make a DIFFERENT hypothesis fail rather than to make the new metric look good.
KA-2 and KA-4 are the discriminators for (a) and (b): the old metric must FAIL them and the new
one must pass, otherwise this tool is not measuring what it claims. KA-5 is the mutation test --
a metric that cannot report a real alias floor is useless no matter how clean it reads.

Run:
    python3.11 analysis/alias_gate.py --selftest
    python3.11 analysis/alias_gate.py --measure            # the amp x OS x constant grid
    python3.11 analysis/alias_gate.py --converge           # 48 k/8x vs a 192 k/8x reference
"""
import argparse
import json
import os
import subprocess
import sys
import tempfile

import numpy as np
from scipy.io import wavfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from parallel import pmap, add_jobs_arg  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RENDER_BIN = os.path.join(ROOT, "build/OfflineRender_artefacts/Release/OfflineRender")

# ---------------------------------------------------------------------------
# Analysis geometry
# ---------------------------------------------------------------------------
FS = 48000.0
M = 1 << 14          # 16384 analysis samples -- the same length the old metric uses
K_BIN = 853          # f0 = K_BIN * FS / M = 2499.0234375 Hz, one bin off the old 2500
F0 = K_BIN * FS / M
LF_HZ = 200.0        # below this, energy is reported as the LF/settling bucket, not as alias

SETTLE_S_OLD = 0.3   # what OSValidationTest discards
SETTLE_S_NEW = 4.0   # 18 tau of the 0.72 Hz output high-passes

SHIPPED_SATNEG = 1.9
PRIOR_SATNEG = 0.76054


def _db(num, den):
    return 10.0 * np.log10((num + 1e-300) / (den + 1e-300))


# ---------------------------------------------------------------------------
# The two metrics
# ---------------------------------------------------------------------------
def metric_old(y, f0=2500.0, fs=FS, n=M):
    """Verbatim reimplementation of OSValidationTest's `aliasFloorDb`.

    Kept exact (Hann, +-3 bin mask, `round(f/f0) >= 1`) so that any difference between the two
    columns of the measurement table is the ANALYSIS and cannot be the render.
    """
    y = np.asarray(y[:n], dtype=float)
    i = np.arange(n)
    win = 0.5 - 0.5 * np.cos(2.0 * np.pi * i / (n - 1))
    mag = np.abs(np.fft.rfft(y * win))
    b = np.arange(len(mag))
    f = b * fs / n
    binhz = fs / n
    nearest = np.round(f / f0)
    is_h = (nearest >= 1.0) & (np.abs(f - nearest * f0) < 3.0 * binhz)
    e = mag ** 2
    e[0] = 0.0                      # the old loop starts at b = 1
    e[len(mag) - 1] = 0.0           # ... and stops before N/2
    return _db(e[~is_h].sum(), e[is_h].sum())


def metric_new(y, k=K_BIN, fs=FS, n=M, lf_hz=LF_HZ):
    """Bin-exact, rectangular-window, LF-separated alias measurement.

    Returns a dict rather than a scalar: the point of the instrument is that the buckets the old
    metric merged stay apart, so a residual can be attributed instead of argued about.
    """
    y = np.asarray(y[:n], dtype=float)
    if len(y) != n:
        raise ValueError(f"metric_new needs exactly {n} samples, got {len(y)}")
    mag = np.abs(np.fft.rfft(y))          # rectangular window: exact for period-n content
    e = mag ** 2
    nbin = len(mag)
    b = np.arange(nbin)

    harm = np.zeros(nbin, dtype=bool)
    order = 1
    while order * k < nbin:
        harm[order * k] = True
        order += 1

    dc = np.zeros(nbin, dtype=bool)
    dc[0] = True
    lf = (b * fs / n < lf_hz) & ~harm & ~dc

    other = ~(harm | dc | lf)
    hp = e[harm].sum()
    return {
        "alias_db": _db(e[other].sum(), hp),          # the headline: inharmonic, LF excluded
        "alias_incl_lf_db": _db(e[other].sum() + e[lf].sum(), hp),
        "lf_db": _db(e[lf].sum(), hp),                # settling / DC-offset residue
        "dc_db": _db(e[0], hp),
        "h_orders": int(harm.sum()),
        "_e": e, "_harm": harm, "_lf": lf, "_other": other,
    }


def strip(d):
    return {kk: vv for kk, vv in d.items() if not kk.startswith("_")}


# ---------------------------------------------------------------------------
# Rendering through the real chain
# ---------------------------------------------------------------------------
def render_sine(amp, os_factor, satneg, fs=FS, k=K_BIN, n=M,
                settle_s=SETTLE_S_NEW, drive=0.85, tmpdir=None):
    """Render a bin-exact sine through OfflineRender; return the settled n-sample tail.

    `--input-ref 1 --output-makeup 1` makes the CLI's gain staging the identity around PedalDSP,
    so `amp` is the same internal-volts amplitude OSValidationTest feeds, and the knob defaults
    below are PedalChain::Params' own defaults -- i.e. this reproduces the test's operating point
    rather than a plausible-looking neighbour of it.
    """
    period = n / k                       # samples per cycle; n samples == exactly k cycles
    settle = int(np.ceil(settle_s * fs / n)) * n     # whole analysis blocks, keeps phase at 0
    total = settle + n + 4096            # a little tail so nothing is read past the end
    t = np.arange(total)
    x = (amp * np.sin(2.0 * np.pi * t / period)).astype(np.float32)

    own_tmp = tmpdir is None
    tmpdir = tmpdir or tempfile.mkdtemp(prefix="alias_gate_")
    tag = f"a{amp}_os{os_factor}_sn{satneg}_fs{int(fs)}_n{n}"
    inp = os.path.join(tmpdir, f"in_{tag}.wav")
    outp = os.path.join(tmpdir, f"out_{tag}.wav")
    wavfile.write(inp, int(fs), x)

    cmd = [RENDER_BIN, "--in", inp, "--out", outp,
           "--os", str(os_factor), "--input-ref", "1", "--output-makeup", "1",
           "--blend", "1", "--level", "1", "--drive", str(drive), "--master", "1",
           "--fit", f"jfetSatNeg={satneg}"]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError(f"OfflineRender failed: {' '.join(cmd)}\n{r.stdout}\n{r.stderr}")
    sr, y = wavfile.read(outp)
    assert sr == int(fs), (sr, fs)
    y = np.asarray(y, dtype=float)
    if y.ndim > 1:
        y = y[:, 0]
    if own_tmp:
        for p in (inp, outp):
            try:
                os.remove(p)
            except OSError:
                pass
    return y[settle:settle + n]


# ---------------------------------------------------------------------------
# GATES
# ---------------------------------------------------------------------------
def _tone(n, k, amp=1.0, phase=0.0, length=None):
    """A tone at bin `k` of an n-point DFT, generated over `length` samples (default n).

    `length` exists so a longer buffer can be sliced at several offsets and every slice is still
    exactly periodic in n -- generating with `np.arange(length)/length` instead would silently
    change the frequency and make an offset-invariance test fail for the wrong reason.
    """
    t = np.arange(length if length is not None else n)
    return amp * np.sin(2.0 * np.pi * k * t / n + phase)


def selftest():
    """Six known-answer gates. Returns (n_fail, lines)."""
    out, fails = [], 0

    def rep(name, ok, detail):
        nonlocal fails
        if not ok:
            fails += 1
        out.append(f"  {'PASS' if ok else 'FAIL'}  {name:<44} {detail}")

    n = M
    # ---- KA-1: a pure bin-exact sine has NO alias content -------------------
    y = _tone(n, K_BIN)
    new = metric_new(y)
    old = metric_old(y, f0=F0)
    rep("KA-1 pure sine, new metric at floor",
        new["alias_db"] < -250.0, f"new = {new['alias_db']:.1f} dB")
    out.append(f"        (old metric on the SAME pure sine: {old:.2f} dB "
               f"-- this is the leakage pedestal, not a chain property)")

    # ---- KA-2: harmonics only. Truth = -inf. THE DISCRIMINATOR FOR (a) ------
    # Two versions of ONE signal: on-grid (bin-exact f0) and off-grid at the shipped 2500 Hz.
    # The old metric's answer must not depend on that choice -- and it does, by ~59 dB.
    ladder = [0.30, 0.20, 0.12, 0.08, 0.05, 0.04, 0.03, 0.02]
    y = _tone(n, K_BIN)
    off = np.sin(2.0 * np.pi * 2500.0 * np.arange(n) / FS)
    for order, a in zip(range(2, 10), ladder):
        y = y + _tone(n, order * K_BIN, a, phase=0.7 * order)
        off = off + a * np.sin(2.0 * np.pi * order * 2500.0 * np.arange(n) / FS + 0.7 * order)
    new = metric_new(y)
    old_exact = metric_old(y, f0=F0)          # same signal, old analysis, bin-exact f0
    old_off = metric_old(off)                 # ... and as the shipped test actually places it
    rep("KA-2 harmonics only, new metric at floor",
        new["alias_db"] < -250.0, f"new = {new['alias_db']:.1f} dB")
    rep("KA-2 old metric IS contaminated (off-grid f0)",
        old_off > -60.0, f"old = {old_off:.2f} dB on a signal with ZERO alias content")
    out.append(f"        (the same signal placed bin-exact reads {old_exact:.2f} dB on the OLD "
               f"metric -- so the {old_off - old_exact:+.0f} dB is the off-grid window skirt,")
    out.append("         which is why the shipped test shows a hard -40.5 dB 'floor' at low drive)")

    # ---- KA-3: calibration. A known inharmonic tone must read its own level --
    target = -35.0
    a = 10 ** (target / 20.0)
    y = _tone(n, K_BIN) + _tone(n, 1000, a)   # 1000 is not a multiple of 853
    got = metric_new(y)["alias_db"]
    rep("KA-3 known -35.0 dB inharmonic tone recovered",
        abs(got - target) < 0.05, f"read {got:.3f} dB")

    # ---- KA-4: a settling LF transient. THE DISCRIMINATOR FOR (b) -----------
    # MasterOut is two ~0.72 Hz high-passes (tau = 0.22 s) and an asymmetric clipper steps them,
    # so the analysis window contains a decaying DC ramp. The fix is the SETTLE LENGTH, not the
    # window: an exponential is not periodic in M, so no window choice makes it disappear -- it
    # has to have decayed away before the read. Both halves of that claim are gated here.
    tau = 0.22 * FS
    dc0 = 0.30
    surv_old = dc0 * np.exp(-SETTLE_S_OLD * FS / tau)   # what survives OSValidationTest's settle
    surv_new = dc0 * np.exp(-SETTLE_S_NEW * FS / tau)   # ... and what survives this tool's
    y_old = _tone(n, K_BIN) + surv_old * np.exp(-np.arange(n) / tau)
    y_new = _tone(n, K_BIN) + surv_new * np.exp(-np.arange(n) / tau)
    # differential, not absolute: the claim is that the transient adds contamination ON TOP of
    # whatever the metric's own leakage pedestal already is, so it is scored against the SAME
    # signal without the transient rather than against a number picked by hand.
    old_clean = metric_old(_tone(n, K_BIN), f0=F0)
    old_trans = metric_old(y_old, f0=F0)
    rep("KA-4 old metric charges the transient to alias",
        old_trans - old_clean > 20.0,
        f"old = {old_trans:.2f} dB vs {old_clean:.2f} without it "
        f"(+{old_trans - old_clean:.1f} dB, residual {surv_old:.3f})")
    rep("KA-4 repaired metric still would, at the OLD settle",
        metric_new(y_old)["alias_db"] > -60.0,
        f"new = {metric_new(y_old)['alias_db']:.2f} dB -- the window is NOT the fix")
    rep("KA-4 the 4 s settle IS the fix",
        metric_new(y_new)["alias_db"] < -150.0,
        f"new = {metric_new(y_new)['alias_db']:.1f} dB (residual {surv_new:.1e})")

    # ---- KA-5: MUTATION. The metric must be able to report a real floor -----
    rng = np.random.default_rng(20260731)
    noise = rng.standard_normal(n)
    sig = _tone(n, K_BIN)
    # scale so inharmonic power sits 17 dB below the fundamental's power
    p_sig = (np.abs(np.fft.rfft(sig)) ** 2)[K_BIN]
    noise = noise * np.sqrt(p_sig * 10 ** (-17.0 / 10.0) / (np.abs(np.fft.rfft(noise)) ** 2).sum())
    got = metric_new(sig + noise)["alias_db"]
    rep("KA-5 mutation: real -17 dB broadband alias IS reported",
        abs(got - (-17.0)) < 0.6, f"read {got:.3f} dB")

    # ---- KA-6: the rectangular read is start-offset invariant ---------------
    y = (_tone(n, K_BIN, length=n + 64)
         + _tone(n, 5 * K_BIN, 0.2, length=n + 64)
         + _tone(n, 1000, 0.01, length=n + 64))
    v = [metric_new(y[s:s + n])["alias_db"] for s in (0, 7, 31, 64)]
    rep("KA-6 read invariant to analysis start offset",
        max(v) - min(v) < 1e-6, f"spread {max(v) - min(v):.2e} dB over 4 offsets")

    return fails, out


# ---------------------------------------------------------------------------
# MEASUREMENT
# ---------------------------------------------------------------------------
AMPS = [0.05, 0.1, 0.2, 0.35, 0.5, 0.7]
FACTORS = [2, 4, 8]


def _measure_one(job):
    amp, fac, sn = job
    y_new = render_sine(amp, fac, sn, settle_s=SETTLE_S_NEW)
    y_old = render_sine(amp, fac, sn, settle_s=SETTLE_S_OLD)
    r = strip(metric_new(y_new))
    r.update({"amp": amp, "os": fac, "satneg": sn,
              "old_db": metric_old(y_old, f0=F0),
              "new_on_old_window_db": metric_new(y_old)["alias_db"],
              "lf_on_old_window_db": metric_new(y_old)["lf_db"]})
    return r


def measure(jobs=None):
    grid = [(a, f, sn) for sn in (SHIPPED_SATNEG, PRIOR_SATNEG) for a in AMPS for f in FACTORS]
    rows = pmap(_measure_one, grid, jobs=jobs)
    return rows


def print_measure(rows):
    by = {(r["satneg"], r["amp"], r["os"]): r for r in rows}
    print("\n  ALIAS/SIGNAL (dB) -- same renders, three analyses")
    print("    old      = OSValidationTest's metric (Hann, +-3 bins, 0.3 s settle)")
    print("    +LF      = repaired metric on the OLD 0.3 s window, LF bucket INCLUDED")
    print("    new      = repaired metric, 4 s settle, LF bucket EXCLUDED  <- the answer")
    print("    lf       = the LF/settling bucket the old metric was charging to alias")
    for sn in (SHIPPED_SATNEG, PRIOR_SATNEG):
        tag = "SHIPPED jfetSatNeg=1.9" if sn == SHIPPED_SATNEG else "PRIOR   jfetSatNeg=0.76054"
        print(f"\n  --- {tag} ---")
        print("     amp |        2x                 |        4x                 |        8x")
        print("         |  old    +LF    new    lf  |  old    +LF    new    lf  |  old    +LF    new    lf")
        for a in AMPS:
            cells = []
            for f in FACTORS:
                r = by[(sn, a, f)]
                cells.append(f"{r['old_db']:6.1f} {r['new_on_old_window_db']:6.1f} "
                             f"{r['alias_db']:6.1f} {r['lf_db']:5.1f}")
            print(f"    {a:.2f} | " + " | ".join(cells))

    print("\n  THE ATTRIBUTED DELTA (shipped - prior), on the repaired metric:")
    print("     amp |    2x      4x      8x   |   old-metric delta at 8x")
    for a in AMPS:
        d = [by[(SHIPPED_SATNEG, a, f)]["alias_db"] - by[(PRIOR_SATNEG, a, f)]["alias_db"]
             for f in FACTORS]
        dold = (by[(SHIPPED_SATNEG, a, 8)]["old_db"] - by[(PRIOR_SATNEG, a, 8)]["old_db"])
        print(f"    {a:.2f} | " + "  ".join(f"{x:+6.2f}" for x in d) + f"   |  {dold:+6.2f}")


# ---------------------------------------------------------------------------
# CONVERGENCE — is the 48 k / 8x inharmonic floor a discretisation artefact?
# ---------------------------------------------------------------------------
def converge(amps=(0.35, 0.5), jobs=None):
    """Compare the 48 k/8x inharmonic floor against a 192 k/8x reference.

    At 192 kHz base the chain's own decimation is 32x further from the audible band, so anything
    it still shows below 24 kHz is NOT fold-down. The bin grid is identical in Hz (192000/65536 ==
    48000/16384), so the two reads are compared over the same frequencies with no resampling.
    """
    jobs_list = [(a, sn) for sn in (SHIPPED_SATNEG, PRIOR_SATNEG) for a in amps]

    def one(job):
        a, sn = job
        y48 = render_sine(a, 8, sn, fs=FS, k=K_BIN, n=M)
        r48 = metric_new(y48)
        y192 = render_sine(a, 8, sn, fs=4 * FS, k=4 * K_BIN, n=4 * M)
        r192 = metric_new(y192, k=4 * K_BIN, fs=4 * FS, n=4 * M)
        # restrict the 192 k read to 0-24 kHz, i.e. the band 48 k can represent at all
        e, harm, other = r192["_e"], r192["_harm"], r192["_other"]
        nb = len(e)
        keep = np.arange(nb) <= (nb - 1) // 4
        ref = _db(e[other & keep].sum(), e[harm & keep].sum())
        return {"amp": a, "satneg": sn, "at48k": r48["alias_db"], "ref192k": ref,
                "excess": r48["alias_db"] - ref}

    rows = pmap(one, jobs_list, jobs=jobs)
    print("\n  CONVERGENCE: 48 k/8x vs a 192 k/8x reference, both read 0-24 kHz")
    print("    excess = how much inharmonic energy the 48 k render has that the 192 k one does")
    print("             NOT -- i.e. the part that is genuinely fold-down.")
    print("     satneg   amp |   48k/8x    192k/8x     excess")
    for r in sorted(rows, key=lambda r: (-r["satneg"], r["amp"])):
        print(f"    {r['satneg']:>8}  {r['amp']:.2f} | {r['at48k']:8.2f}  {r['ref192k']:9.2f}  "
              f"{r['excess']:+9.2f}")
    return rows


# ---------------------------------------------------------------------------
# LOCUS — where the inharmonic energy actually sits, and what predicts it
# ---------------------------------------------------------------------------
def fold_bin(order, k, n):
    """Bin that harmonic `order` of a bin-`k` tone lands on after folding in an n-point DFT."""
    b = (order * k) % n
    return min(b, n - b)


def locus(amp=0.35, os_factor=8, satneg=SHIPPED_SATNEG, top=6, ks=(K_BIN,)):
    """Attribute each dominant inharmonic bin to a harmonic order folding at the OS rate.

    This is the discriminator between "aliasing" and "an autonomous oscillation beating with the
    tone": both put energy at the same bins for ONE f0 (because `n*f0 - m*fs_os` is itself a
    sideband offset), so f0 is MOVED. A fold tracks |n*f0 - m*fs_os| and shifts; a beat note does
    not. Nothing here is fitted -- the predicted bin is arithmetic.
    """
    rows = []
    for k in ks:
        f0 = k * FS / M
        y = render_sine(amp, os_factor, satneg, k=k)
        r = metric_new(y, k=k)
        e, other = r["_e"], r["_other"]
        idx = np.argsort(e * other)[::-1][:top]
        n_centre = int(round(os_factor * FS / f0))
        peaks = []
        for b in idx:
            # nearest harmonic order whose fold lands on this bin
            cands = {o: fold_bin(o, k, M) for o in range(max(1, n_centre - 8), n_centre + 9)}
            best = min(cands, key=lambda o: abs(cands[o] - b))
            peaks.append({"bin": int(b), "hz": b * FS / M,
                          "db_re_h1": 10 * np.log10(e[b] / e[k]),
                          "fold_order": best, "fold_bin": cands[best],
                          "offset_from_h1_hz": b * FS / M - f0})
        rows.append({"k": k, "f0": f0, "alias_db": r["alias_db"], "peaks": peaks})
    return rows


def print_locus(rows, os_factor, satneg):
    print(f"\n  LOCUS of the inharmonic energy  (amp 0.35, {os_factor}x, jfetSatNeg={satneg})")
    print(f"    fold_bin = |order*f0 - m*{os_factor}*fs| expressed as an M-point bin -- ARITHMETIC,")
    print("    not a fit. If it tracks across f0, the energy is fold-down; if the offset from H1")
    print("    is instead constant, it is a beat note against something autonomous.")
    for r in rows:
        print(f"\n    f0 = {r['f0']:.2f} Hz   alias = {r['alias_db']:.2f} dB")
        print("        bin       Hz    dB re H1 |  fold order  predicted bin  |  offset from H1")
        for p in r["peaks"]:
            hit = "==" if p["bin"] == p["fold_bin"] else "!="
            print(f"      {p['bin']:5d} {p['hz']:9.2f}  {p['db_re_h1']:9.2f} |  H{p['fold_order']:<9d}"
                  f" {p['fold_bin']:6d} {hit}   |  {p['offset_from_h1_hz']:+10.2f} Hz")


# ---------------------------------------------------------------------------
# TONE SWEEP — is the bad number a rare coincidence or the normal case?
# ---------------------------------------------------------------------------
SWEEP_KS = [68, 102, 137, 171, 205, 239, 273, 341, 410, 512, 614, 683, 785, 853,
            956, 1024, 1109, 1229, 1365, 1502, 1706]


def sweep(os_factors=(2, 8), amp=0.35, jobs=None):
    grid = [(k, f, sn) for sn in (SHIPPED_SATNEG, PRIOR_SATNEG) for f in os_factors for k in SWEEP_KS]

    def one(job):
        k, f, sn = job
        y = render_sine(amp, f, sn, k=k)
        r = metric_new(y, k=k)
        return {"k": k, "f0": k * FS / M, "os": f, "satneg": sn, "alias_db": r["alias_db"]}

    rows = pmap(one, grid, jobs=jobs)
    by = {(r["satneg"], r["os"], r["k"]): r["alias_db"] for r in rows}

    # A fundamental that exactly divides fs puts every harmonic AND every fold on a harmonic bin,
    # so inharmonic content is impossible BY CONSTRUCTION and the row reads -200 dB and below.
    # Flag and exclude, rather than let a spectacular meaningless number into a median.
    def degenerate(k):
        return abs(FS / (k * FS / M) - round(FS / (k * FS / M))) < 1e-9

    live = [k for k in SWEEP_KS if not degenerate(k)]
    print(f"\n  TONE SWEEP: alias/signal (dB) vs fundamental, amp {amp}")
    print("    Every f0 is bin-exact, so no row carries the off-grid pedestal.")
    print(f"    [deg] = f0 divides fs exactly -> no fold can be inharmonic; excluded from the "
          f"summary ({len(SWEEP_KS) - len(live)} of {len(SWEEP_KS)} rows).")
    hdr = "      f0 (Hz) |" + "".join(f"  {f}x ship  {f}x prior  delta |" for f in os_factors)
    print(hdr)
    for k in SWEEP_KS:
        cells = []
        for f in os_factors:
            s, p = by[(SHIPPED_SATNEG, f, k)], by[(PRIOR_SATNEG, f, k)]
            cells.append(f" {s:8.1f}  {p:9.1f} {s - p:+6.1f} |")
        print(f"    {k * FS / M:9.1f} |" + "".join(cells)
              + ("  [deg]" if degenerate(k) else ""))
    for f in os_factors:
        s = np.array([by[(SHIPPED_SATNEG, f, k)] for k in live])
        p = np.array([by[(PRIOR_SATNEG, f, k)] for k in live])
        print(f"    {f}x  median ship {np.median(s):6.1f}  prior {np.median(p):6.1f}   "
              f"worst ship {s.max():6.1f}  prior {p.max():6.1f}   "
              f"median delta {np.median(s - p):+5.2f}  worst delta {(s - p).max():+5.2f}")
    return rows


# ---------------------------------------------------------------------------
# PERIODICITY — separates deterministic fold-down from an aperiodic regime
# ---------------------------------------------------------------------------
def periodicity(amp=0.35, os_factors=(2, 8), jobs=None):
    """Is the settled output actually periodic in M samples?

    The bin-exact stimulus is periodic in M, and the chain is time-invariant, so a WELL-BEHAVED
    model's settled output must repeat exactly every M samples. It does not have to put its energy
    on harmonic bins to do that -- a subharmonic or chaotic regime is still a regime -- so this
    test separates two things the spectrum alone cannot:

      residual ~ 1e-9  ->  exactly periodic; every inharmonic bin is deterministic FOLD-DOWN.
      residual >> 0    ->  the output does not repeat at all; the inharmonic energy is an
                           APERIODIC regime of the discrete map, which no amount of window or
                           mask arithmetic will explain and which oversampling does not fix.

    Run it before attributing any inharmonic reading to aliasing.
    """
    grid = [(k, f, sn) for sn in (SHIPPED_SATNEG, PRIOR_SATNEG) for f in os_factors
            for k in SWEEP_KS]

    def one(job):
        k, f, sn = job
        n = M
        settle = int(np.ceil(SETTLE_S_NEW * FS / n)) * n
        y = _render_raw(amp, f, sn, k, settle + 2 * n + 4096)
        a, b = y[settle:settle + n], y[settle + n:settle + 2 * n]
        rms = max(float(np.sqrt(np.mean(a ** 2))), 1e-30)
        return {"k": k, "f0": k * FS / M, "os": f, "satneg": sn,
                "resid": float(np.sqrt(np.mean((b - a) ** 2)) / rms),
                "alias_db": metric_new(a, k=k)["alias_db"]}

    rows = pmap(one, grid, jobs=jobs)
    by = {(r["satneg"], r["os"], r["k"]): r for r in rows}
    print(f"\n  PERIODICITY vs FOLD-DOWN, amp {amp}   (resid = ||y[n+M] - y[n]|| / ||y||)")
    print("    resid ~1e-9 = exactly periodic (float32 WAV floor) -> deterministic fold-down")
    print("    resid >1e-4 = APERIODIC regime; the spectrum cannot be read as aliasing")
    hdr = "      f0 (Hz) |" + "".join(f"   {f}x ship        {f}x prior    |" for f in os_factors)
    print(hdr + "\n              |" + "".join("  alias   resid   alias   resid |" for _ in os_factors))
    for k in SWEEP_KS:
        cells = []
        for f in os_factors:
            for sn in (SHIPPED_SATNEG, PRIOR_SATNEG):
                r = by[(sn, f, k)]
                cells.append(f" {r['alias_db']:7.1f} {r['resid']:7.1e}")
        print(f"    {k * FS / M:9.1f} |" + "".join(cells))
    for f in os_factors:
        for sn in (SHIPPED_SATNEG, PRIOR_SATNEG):
            res = np.array([by[(sn, f, k)]["resid"] for k in SWEEP_KS])
            print(f"    {f}x jfetSatNeg={sn}: aperiodic (resid > 1e-4) in {(res > 1e-4).sum()}"
                  f"/{len(res)} tones, worst {res.max():.2e}")
    return rows


def _render_raw(amp, os_factor, satneg, k, total, fs=FS, n=M, drive=0.85):
    """Render `total` samples of a bin-exact sine and return the whole output (no windowing)."""
    tmpdir = tempfile.mkdtemp(prefix="alias_gate_")
    x = (amp * np.sin(2.0 * np.pi * k * np.arange(total) / n)).astype(np.float32)
    inp, outp = os.path.join(tmpdir, "i.wav"), os.path.join(tmpdir, "o.wav")
    wavfile.write(inp, int(fs), x)
    cmd = [RENDER_BIN, "--in", inp, "--out", outp, "--os", str(os_factor),
           "--input-ref", "1", "--output-makeup", "1", "--blend", "1", "--level", "1",
           "--drive", str(drive), "--master", "1", "--fit", f"jfetSatNeg={satneg}"]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError(f"OfflineRender failed\n{r.stderr}")
    _, y = wavfile.read(outp)
    y = np.asarray(y, dtype=float)
    return y[:, 0] if y.ndim > 1 else y


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--selftest", action="store_true")
    ap.add_argument("--measure", action="store_true")
    ap.add_argument("--converge", action="store_true")
    ap.add_argument("--locus", action="store_true",
                    help="attribute the inharmonic peaks to folded harmonic orders, at 3 f0")
    ap.add_argument("--sweep", action="store_true",
                    help="alias floor vs fundamental, shipped vs prior jfetSatNeg")
    ap.add_argument("--periodicity", action="store_true",
                    help="deterministic fold-down vs an aperiodic regime, per tone")
    ap.add_argument("--json", default=None, help="write the measured rows here")
    add_jobs_arg(ap)
    a = ap.parse_args()

    if not (a.selftest or a.measure or a.converge or a.locus or a.sweep or a.periodicity):
        ap.error("pick at least one of --selftest / --measure / --converge / --locus / --sweep"
                 " / --periodicity")

    print(f"  geometry: fs = {FS:.0f}  M = {M}  K = {K_BIN}  f0 = {F0:.4f} Hz  "
          f"bin = {FS / M:.4f} Hz")

    rc = 0
    if a.selftest:
        print("\n  SELF-TEST (known-answer gates)")
        fails, lines = selftest()
        print("\n".join(lines))
        print(f"\n  {'ALL GATES PASS' if fails == 0 else f'{fails} GATE FAILURE(S)'}")
        rc |= (1 if fails else 0)
        if fails:
            return rc   # never measure with a failing instrument

    out = {}
    if a.measure:
        if not os.path.exists(RENDER_BIN):
            sys.exit(f"OfflineRender not built: {RENDER_BIN}")
        rows = measure(jobs=a.jobs)
        print_measure(rows)
        out["measure"] = rows
    if a.locus:
        rows = locus(ks=(683, K_BIN, 1109))
        print_locus(rows, 8, SHIPPED_SATNEG)
        out["locus"] = rows
    if a.sweep:
        out["sweep"] = sweep(jobs=a.jobs)
    if a.periodicity:
        out["periodicity"] = periodicity(jobs=a.jobs)
    if a.converge:
        out["converge"] = converge(jobs=a.jobs)
    if a.json and out:
        with open(a.json, "w") as f:
            json.dump(out, f, indent=1)
        print(f"\n  wrote {a.json}")
    return rc


if __name__ == "__main__":
    sys.exit(main())
